// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLaTDWKEwqvQ5h6dmHkbHjI9vGjacTiyE',
    appId: '1:23828552690:web:04d3ae6a7f8b1f05fb696b',
    messagingSenderId: '23828552690',
    projectId: 'gymm-rat-f9a19',
    authDomain: 'gymm-rat-f9a19.firebaseapp.com',
    storageBucket: 'gymm-rat-f9a19.appspot.com',
    measurementId: 'G-7REG1NRJX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSBl8yMQhi9TU2D1DXVcFVdp1DjBmZA8',
    appId: '1:23828552690:android:770a75cc617f1529fb696b',
    messagingSenderId: '23828552690',
    projectId: 'gymm-rat-f9a19',
    storageBucket: 'gymm-rat-f9a19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSeR6CYw0wzbhGj4esGnJ70YXU8HLLPqE',
    appId: '1:23828552690:ios:eb5a04c4164d20d6fb696b',
    messagingSenderId: '23828552690',
    projectId: 'gymm-rat-f9a19',
    storageBucket: 'gymm-rat-f9a19.appspot.com',
    androidClientId: '23828552690-nqke1ggf0caaksevn4lrj916m6134mb9.apps.googleusercontent.com',
    iosClientId: '23828552690-jcdb2o42i131bf7og5ip18t6pfu5rf29.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymmRat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSeR6CYw0wzbhGj4esGnJ70YXU8HLLPqE',
    appId: '1:23828552690:ios:e86996c8e664143cfb696b',
    messagingSenderId: '23828552690',
    projectId: 'gymm-rat-f9a19',
    storageBucket: 'gymm-rat-f9a19.appspot.com',
    androidClientId: '23828552690-nqke1ggf0caaksevn4lrj916m6134mb9.apps.googleusercontent.com',
    iosClientId: '23828552690-luce2dgrva7qh04jg5rnio384jftcr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymmRat.RunnerTests',
  );
}
